### ISSUE TITLE
Deployment works but page fails due to CORS errors on static assets like favicon/manifest

### ISSUE THREAD

**Issue by shealan** [wan2land/serverless-nuxt#144]
As far as I can see the CORS settings are correct as they are defined in the serverless.yml doc. I confirmed it did indeed create the xml CORS settings on the bucket. The files do exist and are accessible.

Anyone else seen this?

**Comment by wan2land** [comment]
The favicon and manifest files are not saved in s3, it is called from labmda.
If you changed the settings related to favicon or manifest in the `nuxt.config.js` file, show me the file.

**Comment by shealan** [comment]
Here is the deployment url: https://yjdiw86zpj.execute-api.ap-southeast-2.amazonaws.com/dev

This was a new new Nuxt Create App project. The serverless file looks like this:

```yml
service:
  name: nuxt-serverless-tmp

plugins:
  - serverless-nuxt-plugin

resources:
  Resources:
    AssetsBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.nuxt.bucketName}
        CorsConfiguration:
          CorsRules:
            - AllowedMethods:
              - GET
              - HEAD
              AllowedOrigins:
              - "*"

provider:
  name: aws
  region: ap-southeast-2
  stage: ${opt:stage, 'dev'}
  runtime: nodejs12.x
  environment:
    NODE_ENV: ${file(.env.${self:provider.stage}.yml):NODE_ENV}

custom:
  nuxt:
    version: v0.0.1-alpha
    bucketName: nuxt-serverless-tmp-${self:provider.stage}

functions:
  nuxt:
    handler: handler.render
    events:
      - schedule: rate(5 minutes)
      - http: ANY /
      - http: ANY /{proxy+}
```

I deployed the project again from scratch with no changes to any aws config via the console.
