### ISSUE TITLE
serverless.yml can't get environment variable

### ISSUE THREAD

**Issue by hmaesta** [wan2land/serverless-nuxt#214]
Hello! 
First of all, thank you for the nice and complete tutorial. Absolutely new to serverless here and it was very helpful.

When trying to deploy I received:
```
  Access Denied ------------------------------------------
 
  AccessDenied: Access Denied
```

Running `SLS_DEBUG=1 serverless deploy` shows that:

```
 Serverless Warning --------------------------------------

  A valid environment variable to satisfy the declaration 'env:NODE_ENV' could not be found.
 
 Serverless Warning --------------------------------------
 
  A valid environment variable to satisfy the declaration 'env:API_URL' could not be found.
 
 Serverless Warning --------------------------------------
 
  A valid environment variable to satisfy the declaration 'env:DOMAIN_NAME' could not be found.
 
 (...)
```

My files:

#### .env-cmdrc
```js
module.exports = {
  local: {
    NODE_ENV: 'development',
    PORT: '8080',
    API_URL: 'http://localhost:8080/api',
  },
  prod: {
    DOMAIN_NAME: 'app.domain.com',
    NODE_ENV: 'production',
    NUXT_TELEMETRY_DISABLED: '1',
    API_URL: 'https://domain.com/api',
  },
}
```

#### serverless.yml
```yml
provider:
  name: aws
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  runtime: nodejs12.x
  environment:
    NODE_ENV: ${env:NODE_ENV}
    API_URL: ${env:API_URL}
```

On `serverless.yml` if I change the variables to strings it works. For example: `'production'` instead of `${env:NODE_ENV}`.

Perhaps my `.env-cmdrc` is not "discoverable"? 
To deploy I am using `env-cmd -e prod sls deploy --stage prod`
