### ISSUE TITLE
resolved path for assets is wrong

### ISSUE THREAD

**Issue by dasraab** [wan2land/serverless-nuxt#36]
It seems like there is an issue with resolving the correct path for the deployed assets. In my first test my site loads but all the linked resources (css, js) point to the wrong location.

https://s3.undefined.amazonaws.com/myproject-dev/v0.0.1/a6b369ff4ddca0b87aeb.js
seems like we have some undefined var somewhere, any idea where this could come from?

shouldn't the link be something like this anyways?
https://myproject-dev.s3.amazonaws.com/v0.0.1/a6b369ff4ddca0b87aeb.js

**Comment by wan2land** [comment]
`undefined` is Region. Please include Region in your AWS credentials.

**Comment by wan2land** [comment]
https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingBucket.html

Bucket names can contain ".", So I implemented them as "Path-Style Access"
I read a recent S3 document and say that "Path-Style Access" is not supported after September 2020. Consider "Virtual Hosted Style Access".

**Comment by wan2land** [comment]
https://github.com/wan2land/serverless-nuxt/issues/37

**Comment by dasraab** [comment]
my ~/.aws/credentials file looks like this
```
[default]
aws_access_key_id = xxxx
aws_secret_access_key = xxx
region = eu-central-1
```

however if i dump awsCredentials in [here](https://github.com/wan2land/serverless-nuxt/blob/c525b21bf19e6656a93979dd7ba1a0eb2f255aaf/packages/serverless-nuxt-plugin/src/index.js#L51) i do get this

```
{
  credentials: SharedIniFileCredentials {
    expired: false,
    expireTime: null,
    refreshCallbacks: [],
    accessKeyId: 'xxxxxx',
    sessionToken: undefined,
    filename: undefined,
    profile: 'default',
    disableAssumeRole: false,
    preferStaticCredentials: false,
    tokenCodeFn: [Function],
    httpOptions: null
  }
}

```

and awsCredentials.region ist still undefined

**Comment by wan2land** [comment]
oh, I misunderstand. there are two way to solve this problem.

1. use command with region `sls deploy --stage dev --region ap-northeast-2`
2. set region on your `serverless.yml` file below:

```yml
provider:
  name: aws
  region: us-east-1 # this field is used for the assets files s3 path.
  stage: ${opt:stage, 'dev'}
  runtime: nodejs12.x
```

**Comment by dasraab** [comment]
i don't think thats the problem. The "provider" part of my serverless.yml file looks like this. So there is already a fallback-value for "region"
``` yml
provider:
     name: aws
     region: ${opt:region, 'eu-central-1'}
     profile: default
     stage: ${opt:stage, 'dev'}
     runtime: nodejs12.x
     environment:
       NODE_ENV: ${file(.env.${self:provider.stage}.yml):NODE_ENV}
   ```

**Comment by wan2land** [comment]
What is the serverless version and nodejs version?

**Comment by dasraab** [comment]
Node:
Version 13.7.0

Serverless
Framework Core: 1.63.0
Plugin: 3.3.0
SDK: 2.3.0
Components Core: 1.1.2
Components CLI: 1.4.0

Hope that helps!

**Comment by wan2land** [comment]
For now, using a version of Serverless lower than 1.63.0 solves this. I will improve it to support 1.63.0 and above!

Thank you for your report!

Related commit:
https://github.com/serverless/serverless/commit/c7fea34e859fd9b4cd19118a518ae68d140728e5#diff-271ef5d492727880dcac1b94a86c878d

**Comment by wan2land** [comment]
Or, You can use "cdnPath".

```yml
custom:
  nuxt:
    version: v1.0.0-alpha
    bucketName:
    assetsPath:
    cdnPath: "https://myproject-dev.s3.amazonaws.com"
```
