### ISSUE TITLE
Cannot load JS file

### ISSUE THREAD

**Issue by thenewspacesky5456** [wan2land/serverless-nuxt#74]
Loading failed for the <script> with source “https://aws-xxx-003-dev.s3.amazonaws.com/v0.0.1-alpha/469b3fd99b54ef897cae.js”. login:14:1
Loading failed for the <script> with source “https://aws-xxx-003-dev.s3.amazonaws.com/v0.0.1-alpha/e16c041dab9ddcaeb8b5.js”. login:14:1
downloadable font: download failed (font-family: "Material Design Icons" style:normal weight:400 stretch:100 src index:1): status=2152398850 source: https://aws-xxx-003-dev.s3.amazonaws.com/v0.0.1-alpha/fonts/d006653.woff2
Loading failed for the <script> with source “https://aws-xxx-003-dev.s3.amazonaws.com/v0.0.1-alpha/744b1393911999f725fb.js”. login:14:1
Loading failed for the <script> with source “https://aws-xxx-003-dev.s3.amazonaws.com/v0.0.1-alpha/e16c041dab9ddcaeb8b5.js”. login:14:1
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://aws-xxx-003-dev.s3.amazonaws.com/v0.0.1-alpha/fonts/f511123.ttf. (Reason: CORS request did not succeed).

downloadable font: download failed (font-family: "Material Design Icons" style:normal weight:400 stretch:100 src index:1): status=2152398868 source: https://aws-xxx-003-dev.s3.amazonaws.com/v0.0.1-alpha/fonts/d006653.woff2
Loading failed for the <script> with source “https://aws-xxx-003-dev.s3.amazonaws.com/v0.0.1-alpha/469b3fd99b54ef897cae.js”. login:14:1
Loading failed for the <script> with source “https://aws-xxx-003-dev.s3.amazonaws.com/v0.0.1-alpha/744b1393911999f725fb.js”. login:14:1
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://aws-xxx-003-dev.s3.amazonaws.com/v0.0.1-alpha/fonts/f511123.ttf. (Reason: CORS request did not succeed).

And other issue:
+ Load file slowly too
<img width="1085" alt="Screen Shot 2020-04-13 at 10 20 27 AM" src="https://user-images.githubusercontent.com/59953556/79089571-cef20c80-7d70-11ea-9f7a-ed57b796a1d2.png">

**tailwind.config.js**
```
const pkg = require("./package.json")

// require('dotenv').config()
module.exports = {
  mode: 'universal',
  /*
   ** Headers of the page
   */

  head: {
    title: 'xxx',
    meta: [
      { charset: 'utf-8' },
      { name: 'viewport', content: 'width=device-width, initial-scale=1' }

    ],
    link: [{ rel: 'icon', type: 'image/x-icon', href: '/favicon.ico' }],

  },
  /*
   ** Customize the progress-bar color
   */
  loading: '~/components/core/loading.vue',
  /*
   ** Global CSS
   */
  css: [
    '@mdi/font/css/materialdesignicons.css',
    '~/assets/scss/main.scss',
    '~/assets/css/ui-theme/theme/index.css',
  ],
  /*
   ** Plugins to load before mounting the App
   */
  plugins: [
    '~/plugins/element-ui.js',
    '~/plugins/EventBus.js',
    '~/plugins/axios',
    '~/plugins/vue-lodash.js',
    '~/plugins/vue-js-modal.js',
    '@/plugins/vue2-filters',
    {
      src: '~/plugins/vue-line-clamp.js',
      ssr: false
    },
    {
      src: '~/plugins/vue-lazyload.js',
      ssr: true
    },
    {
      src: '~/plugins/vue-zoom-on-hover.js',
      ssr: true
    },
    {
      src: '~/plugins/vue-star-rating.js',
      ssr: false
    },
    {
      src: '~/plugins/vue-moment.js',
      ssr: true
    },
    {
      src: '~/plugins/vue-country-flag.js',
      ssr: false
    },
    {
      src: '~/plugins/vuex-persistedstate.js',
      ssr: false
    },
    {
      src: '~/plugins/load-image.js',
      ssr: true
    },
    {
      src: '~/plugins/my-tracking.js',
      ssr: false
    },
    {
      src: '~/plugins/vue-countdown.js',
      ssr: false
    },
    {
      src: '~/plugins/vue-read-more.js',
      ssr: false
    },
    {
      src: '~/plugins/vue-carousel.js',
      ssr: false
    }
  ],
  /*
   ** Nuxt.js dev-modules
   */
  buildModules: [
    // Doc: https://github.com/nuxt-community/eslint-module
    // ['@nuxtjs/eslint-module', { fix: true }],
    // Doc: https://github.com/nuxt-community/nuxt-tailwindcss
    '@nuxtjs/tailwindcss'
  ],
  /*
   ** Nuxt.js modules
   */
  modules: [
    '@nuxtjs/axios',
    '@nuxtjs/pwa',
    '@nuxtjs/auth',
    '@nuxtjs/sitemap',
    ['@nuxtjs/google-tag-manager', { id: 'GTM-xxxx' }]
  ],


  sitemap: {

    path: '/sitemapindex.xml',
    sitemaps: [
      {
        exclude: [
          '/shopcart/**',
          '/login',
        ],
        path: '/sitemap-home.xml',
        routes: [
          '/',
          '/wholesale'
        ],
        defaults: {
          changefreq: 'daily',
          priority: 1,
          lastmod: new Date(),
          lastmodrealtime: true
        },
      }
    ]

  },

  purgeCSS: {
    whitelistPatterns: [/el-.+$/],
    whitelistPatternsChildren: [/el-.+$/]
  },

  axios: {
    baseURL: 'https://api.xxx.com/api'
  },
  auth: {
    redirect: {
      logout: '/login',
      login: '/login',
    },
    rewriteRedirects: true,
    fullPathRedirect: true,

    strategies: {
      local: {
        endpoints: {
          login: { url: '/user/login', method: 'post', propertyName: 'token' },
          user: { url: '/user/me', method: 'get', propertyName: 'user' },
          logout: { url: '/user/logout', method: 'get' }
        },
        tokenRequired: true,
        tokenType: 'bearer'
      }
    }
  },

  /*
   ** Build configuration
   */
  build: {
    transpile: [/^element-ui/],
    /*
     ** You can extend webpack config here
     */
    extend(config, ctx) {


    }
  }
}
```
**serverless.yml**
```
service:
  name: aws-xxx-serverless-003

plugins:
  - serverless-nuxt-plugin

resources:
  Resources:
    AssetsBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.nuxt.bucketName}
        CorsConfiguration:
          CorsRules:
            - AllowedMethods:
              - GET
              - HEAD
              AllowedOrigins:
              - "*"

provider:
  name: aws
  region: us-east-1 # this field is used for the assets files s3 path.
  stage: ${opt:stage, 'dev'}
  runtime: nodejs12.x
  environment:
    NODE_ENV: ${file(.env.${self:provider.stage}.yml):NODE_ENV}

custom:
  nuxt:
    version: v0.0.1-alpha
    # If the version is defined in the `package.json` file
    # version: v${file(./package.json):version}
    bucketName: aws-xxx-003-${self:provider.stage}

functions:
  nuxt:
    handler: handler.render
    events:
      # warm up
      # - schedule: rate(5 minutes)
      - http: ANY /
      - http: ANY /{proxy+}
```

**package.json**
```
{
  "name": "frontend_sh001",
  "version": "1.0.0",
  "description": "My tiptop Nuxt.js project",
  "author": "tomtony",
  "private": true,
  "scripts": {
    "dev": "nuxt",
    "build": "nuxt build",
    "start": "nuxt start",
    "generate": "nuxt generate",
    "lint": "eslint --ext .js,.vue --ignore-path .gitignore .",
    "lintfix": "eslint --fix --ext .js,.vue --ignore-path .gitignore ."
  },
  "lint-staged": {
    "*.{js,vue}": "eslint"
  },
  "dependencies": {
    "@chenfengyuan/vue-countdown": "^1.1.5",
    "@mdi/font": "^4.9.95",
    "@nuxtjs/auth": "^4.9.0",
    "@nuxtjs/axios": "^5.9.7",
    "@nuxtjs/google-tag-manager": "^2.3.2",
    "@nuxtjs/pwa": "^3.0.0-beta.20",
    "@nuxtjs/robots": "^2.4.2",
    "@nuxtjs/sentry": "^3.3.1",
    "@nuxtjs/sitemap": "^2.2.0",
    "aws-serverless-express": "^3.3.8",
    "element-ui": "^2.13.0",
    "fastify": "^2.13.1",
    "fastify-static": "^2.6.0",
    "lodash": "^4.17.15",
    "nuxt-start": "^2.12.2",
    "serverless-nuxt": "^1.1.1",
    "vue": "^2.6.11",
    "vue-carousel": "^0.18.0",
    "vue-country-flag": "^1.3.1",
    "vue-js-modal": "^1.3.33",
    "vue-lazyload": "^1.3.3",
    "vue-line-clamp": "^1.3.2",
    "vue-lodash": "^2.1.2",
    "vue-moment": "^4.1.0",
    "vue-read-more": "^1.1.1",
    "vue-star-rating": "^1.6.1",
    "vue-stripe-elements-plus": "^0.3.2",
    "vue2-filters": "^0.8.0",
    "vuex-map-fields": "^1.4.0",
    "vuex-persistedstate": "^2.7.1"
  },
  "devDependencies": {
    "@nuxtjs/dotenv": "^1.4.1",
    "@nuxtjs/eslint-config": "^1.0.1",
    "@nuxtjs/eslint-module": "^1.0.0",
    "@nuxtjs/tailwindcss": "^1.4.0",
    "babel-eslint": "^10.1.0",
    "eslint": "^6.8.0",
    "eslint-config-prettier": "^4.1.0",
    "eslint-plugin-nuxt": "^0.5.2",
    "eslint-plugin-prettier": "^3.1.2",
    "husky": "^2.6.0",
    "lint-staged": "^8.2.1",
    "node-sass": "^4.13.1",
    "nuxt": "^2.12.2",
    "prettier": "^1.19.1",
    "sass-loader": "^8.0.2",
    "serverless": "^1.63",
    "serverless-apigw-binary": "^0.4.4",
    "serverless-nuxt-plugin": "^1.1",
    "serverless-offline": "^6.1.4"
  }
}
```

@wan2land Could you help  me?
Thanks

**Comment by thenewspacesky5456** [comment]
@ferdinandfrank @mz3 .Could you help me? Please

**Comment by wan2land** [comment]
Please tell me the exact version of `serverless-nuxt-plugin`. Check the `package-lock.json` file.

**Comment by thenewspacesky5456** [comment]
Hello @wan2land 
"serverless-nuxt-plugin": {
"version": "1.1.0",
"resolved": "https://registry.npmjs.org/serverless-nuxt-plugin/-/serverless-nuxt-plugin-1.1.0.tgz",
"integrity": "sha512-BPKhBA2+SlBzaCxqS2ytY1gPDN2drq/ijVFz4wM2aBf3a9ck7kLg4A/lncAGqD4jNJ/Zf9BJvtDgdTim6RA2Vg==",
"dev": true,
"requires": {
"chalk": "^3.0.0",
"globby": "^11.0.0",
"mime-types": "^2.1.24"
},

[package-lock.txt](https://github.com/wan2land/serverless-nuxt/files/4472726/package-lock.txt)

**Comment by wan2land** [comment]
When updating a new version, you need to change the version numbering.
For example, if the recent release was `v0.0.1-alph`, then the next release should change the value to `v0.0.1-alph2`.

Change the version and redeploy.


The problem with slow S3 downloads is strange.
Is your region "us-east-1" right? Check S3 Region.

https://docs.aws.amazon.com/general/latest/gr/s3.html

**Comment by thenewspacesky5456** [comment]
Hello @wan2land 
Is your region "us-east-1" right?
--> Yes

**Comment by thenewspacesky5456** [comment]
Hello. @wan2land 
I tried redeployed. But not working
`Loading failed for the <script> with source “https://aws-xxxx-serverless-006dev.s3.amazonaws.com/v0.0.1-alpha1/744b1393911999f725fb.js”. login:14:1`
....
<img width="1314" alt="Screen Shot 2020-04-14 at 10 18 05 AM" src="https://user-images.githubusercontent.com/59953556/79182885-27d9a780-7e3a-11ea-9dd6-3312b87852a0.png">
Could you help me @wan2land ?
Thanks

**Comment by thenewspacesky5456** [comment]
Hello @wan2land 
could you help me make an investigation about this issue?
Thanks

**Comment by thenewspacesky5456** [comment]
Hello @wan2land
could you help me make an investigation about this issue?
Thanks

**Comment by ferdinandfrank** [comment]
@wan2land I guess you are trying to access your static files on S3 directly, right? Maybe your issues can be resolved when you manually setup an AWS CloudFront distribution in front of your S3 bucket .
See this guide: https://aws.amazon.com/de/premiumsupport/knowledge-center/cloudfront-https-requests-s3/

Setting up a CloudFront distribution also has a caching benefit for your resources as well as the option for automatic compression for your static files which will increase your page performance and should therefore fix you "slow loading resources" issue. So it's a good idea to set one up anyways. :) 

Just follow the guide above and insert the URL to your distribution, e.g., d111111abcdef8.cloudfront.net, (or your custom alias) into the `cdnPath` option within your `serverless.yml` file, [as documented here](https://github.com/wan2land/serverless-nuxt#use-custom-url-instead-of-s3-bucket-url).

Let me know if you have issues with the setup.

**Comment by thenewspacesky5456** [comment]
Hello @wan2land 
It's not working. Please help me thanks
<img width="1403" alt="Screen Shot 2020-04-20 at 5 21 32 PM" src="https://user-images.githubusercontent.com/59953556/79741790-09891580-832c-11ea-867c-48cad302941e.png">
Here link access serverless:
https://h7tmen4s70.execute-api.us-east-1.amazonaws.com/dev/login

**Comment by wan2land** [comment]
Since API Gateway does not support binary format properly, all files (except favicon) under static should be moved to assets subdirectory.

For image files, use:

```vue
<template>
  <img src="/assets/img/blabla.png" /><!-- Unavailable -->
  <img :src="require('~/assets/img/blabla.png')" /><!-- Available -->
</template>
```

**Comment by wan2land** [comment]
Oh,

**Comment by wan2land** [comment]
change your cdnPath

```
cdnPath: https://d1il5vg5vwdiq7.cloudfront.net
```

**Comment by thenewspacesky5456** [comment]
Hello @wan2land .
For the deploy on serverless:
When I access any web page then always redirect to the error page.
could you help me make an investigation about this issue?
here link access:
https://2bu3uml5jc.execute-api.us-east-1.amazonaws.com/dev/login

**Comment by wan2land** [comment]
You need to use a domain. :-) 

https://github.com/wan2land/serverless-nuxt/issues/2

**Comment by thenewspacesky5456** [comment]
Hello @wan2land 
how to detect mobile device and redirect to mobile site?
Many thanks

**Comment by wan2land** [comment]
Serverless is not different from normal server. You can use the same method that was used in the existing Nuxt.

I think you can use this library. https://www.npmjs.com/package/@nuxtjs/device

Problems such as mobile detection seem to be outside the scope of this issue. If there are no more issues related to this library, I will close the issues.

**Comment by thenewspacesky5456** [comment]
Hello @wan2land 
How to use dotenv in serverless-nuxt?
```
{
    "errorType": "Runtime.ImportModuleError",
    "errorMessage": "Error: Cannot find module 'dotenv'\nRequire stack:\n- /var/task/nuxt.config.js\n- /var/task/handler.js\n- /var/runtime/UserFunction.js\n- /var/runtime/index.js",
    "stack": [
        "Runtime.ImportModuleError: Error: Cannot find module 'dotenv'",
        "Require stack:",
        "- /var/task/nuxt.config.js",
        "- /var/task/handler.js",
        "- /var/runtime/UserFunction.js",
        "- /var/runtime/index.js",
        "    at _loadUserApp (/var/runtime/UserFunction.js:100:13)",
        "    at Object.module.exports.load (/var/runtime/UserFunction.js:140:17)",
        "    at Object.<anonymous> (/var/runtime/index.js:43:30)",
        "    at Module._compile (internal/modules/cjs/loader.js:1158:30)",
        "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)",
        "    at Module.load (internal/modules/cjs/loader.js:1002:32)",
        "    at Function.Module._load (internal/modules/cjs/loader.js:901:14)",
        "    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)",
        "    at internal/main/run_main_module.js:18:47"
    ]
}
```

**Comment by ferdinandfrank** [comment]
@thenewspacesky5456 Do you have `dotenv` under your `dependencies` in `package.json`? It must be under `dependencies` not `devDependencies`.

**Comment by thenewspacesky5456** [comment]
Hello @thenewspacesky5456 
I moved dotenv to dependencies. I'm seeing another error

```

16:17:10
START RequestId: b3dc2f46-9fb6-49cb-9cb5-2da654dacaa8 Version: $LATEST

16:17:10
ERROR Cannot find module 'vue' from '/var/task'

16:17:10
at Function.module.exports [as sync] (node_modules/resolve/lib/sync.js:74:15)

16:17:10
at node_modules/nuxt-start/node_modules/vue-server-renderer/build.prod.js:1:77713

16:17:10
at Object.<anonymous> (server.js:1:1458)

16:17:10
at l (server.js:1:194)

16:17:10
at Module.<anonymous> (server.js:1:235618)

16:17:10
at l (server.js:1:194)

16:17:10
at Object.<anonymous> (server.js:1:5341)

16:17:10
at l (server.js:1:194)

16:17:10
at server.js:1:1422

16:17:10
at Object.<anonymous> (server.js:1:1432)

16:17:10
END RequestId: b3dc2f46-9fb6-49cb-9cb5-2da654dacaa8
```

**Comment by thenewspacesky5456** [comment]
Hello @wan2land 
For  serverless-domain-manager
Error: Unable to create basepath mapping for service 2
```

  Error: Error: Unable to create basepath mapping.
      at ServerlessCustomDomain.<anonymous> (/Users/xxxx/Desktop/xxxx/source_code/admin-serverless/node_modules/serverless-domain-manager/dist/index.js:519:23)
      at Generator.throw (<anonymous>)
      at rejected (/Users/xxxx/Desktop/xxxx/source_code/web-tshirt-admin-serverless/node_modules/serverless-domain-manager/dist/index.js:5:65)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

Service 1: (Working)
```
  customDomain:
    domainName: example.com
    stage: ${self:provider.stage}
    certificateName: '*example.com'
    createRoute53Record: true
    endpointType: 'regional'
    securityPolicy: tls_1_2
```

service 2: (Error: Unable to create basepath mapping.)
```
  customDomain:
    domainName: backend.example.com
    stage: ${self:provider.stage}
    basePath: admin
    certificateName: 'backend.example.com'
    createRoute53Record: true
    endpointType: 'regional'
    securityPolicy: tls_1_2
```

**Comment by ferdinandfrank** [comment]
@thenewspacesky5456 I think it should work. Did you setup another mapping before? If so, you can try this solution: https://github.com/amplify-education/serverless-domain-manager/issues/242#issuecomment-546933681

**Comment by wan2land** [comment]
I do not recommend using `dotenv`. I think environment variables are better injected from outside than from inside. When configuring, I usually use env-cmd.

This is my **package.json** i used in my recent project.

```json
{
  "name": "myapp-client",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "dev": "env-cmd -e local nuxt",
    "deploy:dev": "env-cmd -e dev sls deploy --stage dev",
    "deploy:prod": "env-cmd -e prod sls deploy --stage prod"
  },
  "dependencies": {
    "nuxt-start": "^2.11.0",
    "serverless-nuxt": "^1.0.0-alpha.1"
  },
  "devDependencies": {
    "env-cmd": "^10.1.0",
    "node-sass": "^4.13.1",
    "nuxt": "^2.11.0",
    "sass-loader": "^8.0.2",
    "serverless": "^1.67.0",
    "serverless-apigw-binary": "^0.4.4",
    "serverless-domain-manager": "^3.3.1",
    "serverless-nuxt-plugin": "^1.0.0-alpha.1"
  }
}
```

**.env-cmdrc.js**

```js

module.exports = {
  local: {
    NODE_ENV: 'development',
    PORT: '3001',
    API_URL: 'http://localhost:12345',
  },
  dev: {
    DOMAIN_NAME: 'dev.myapp.com',
    NODE_ENV: 'development',
    API_URL: 'https://api.dev.myapp.com',
  },
  prod: {
    DOMAIN_NAME: 'myapp.com',
    NODE_ENV: 'production',
    API_URL: 'https://api.myapp.com',
  },
}
```

**serverless.yml**

service:
  name: myapp-client

plugins:
  - serverless-domain-manager
  - serverless-nuxt-plugin
  - serverless-apigw-binary

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  runtime: nodejs12.x
  environment:
    NODE_ENV: ${env:NODE_ENV}
    API_URL: ${env:API_URL}
  
custom:
  customDomain:
    domainName: ${env:DOMAIN_NAME}
  apigwBinary:
    types:
      - 'image/*'
  nuxt:
    version: v${file(./package.json):version}
    bucketName: myapp-client-${self:provider.stage}

resources:
  Resources:
    AssetsBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.nuxt.bucketName}
        CorsConfiguration:
          CorsRules:
            - AllowedMethods:
              - GET
              - HEAD
              AllowedOrigins:
              - "*"

functions:
  nuxt:
    handler: handler.render
    events:
      - schedule: rate(5 minutes)
      - http: ANY /
      - http: ANY /{proxy+}

**Comment by thenewspacesky5456** [comment]
Thanks @wan2land , @ferdinandfrank

**Comment by thenewspacesky5456** [comment]
Hello @wan2land 
I cannot call the api via axios
axios.js plugins
```
import { showError } from '@/common/AppUtils.js'

export default function({ $axios, redirect, store, app }) {
  $axios.setHeader('Content-Type', 'application/json')
  $axios.onRequest((config) => {
    if (app.$auth.getToken('local')) {
      config.headers.common.Authorization = app.$auth.getToken('local')
    }
  })
  $axios.onError((error) => {
    const code = parseInt(error.response && error.response.status)
    if (code === 401) {
      app.$auth.logout()
    } else {
      showError(error.response.data.message)
    }
    return Promise.reject(error)
  })
}
```
Index.vue

```
  async asyncData({ app, $axios, error }) {
    try {
      // console.log(app.$device)
      const todaySuggestionProducts = await $axios.$get(
        '/products'
      )
```
Error:
```
13:06:39
2020-04-28T13:06:39.174Z ba79c228-4fba-4e6e-af87-2bc4889d031c INFO TypeError: Cannot read property 'data' of undefined at server.js:1:595274 at server.js:1:593957 at processTicksAndRejections (internal/process/task_queues.js:97:5) at async asyncData (9b81432fb5e8a30cf197.js:1:32789)
2020-04-28T13:06:39.174Z	ba79c228-4fba-4e6e-af87-2bc4889d031c	INFO	TypeError: Cannot read property 'data' of undefined
    at server.js:1:595274
    at server.js:1:593957
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async asyncData (9b81432fb5e8a30cf197.js:1:32789)
```

**Comment by wan2land** [comment]
create new issue please. :-)

**Comment by cavi21** [comment]
Hi @wan2land hope you're doing great, thanks for the work on this plugin! I'm writing because everything seems to be working fine, but the `cdnPath` on the built seems to not work as expected.

The weird thing is that in the `.nuxt/dist/server/server.js` for example the `__webpack_public_path__` is properly set but when I navigate to the site (I'm using a custom domain) all the assets seems to be loaded from the `/__nuxt/....`

Do you have any idea where to look in order to fix this?

I have in the **nuxt.config.js**:
```js
module.exports = {
  telemetry: false,
  mode: 'universal',
  target: 'server',
  srcDir: 'src/',
  server: {
    port: 4400,
  },
  head: {
    ...
  },
  build: {
    // The "publicPath" value is automatically generated by the serverless-nuxt plug-in
    // If the "publicPath" value is set, delete it.
  },
  buildModules: [
    ['@nuxtjs/google-analytics', { id: 'UA-XXX' }],
    '@nuxtjs/google-fonts',
    '@nuxtjs/tailwindcss',
  ],
}
```

and in the **serverless.yml**
```yml
service: service-name

frameworkVersion: '2'

plugins:
  - serverless-nuxt-plugin
  - serverless-s3-sync
  - serverless-dotenv-plugin
  - serverless-apigw-binary
  - serverless-offline
  - serverless-domain-manager

package:
  individually: true
  excludeDevDependencies: true
  exclude:
    - src/**
    - .nuxt/**
    - package.json
    - package-lock.json
    - .gitignore
    - .env.example
    - node_modules/**
    - src/static/**
  include:
    - .nuxt/dist/**

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: us-east-2
  stage: ${env:STAGE}
  versionFunctions: false
  apiGateway:
    shouldStartNameWithService: true
  environment:
    NODE_ENV: ${env:NODE_ENV}

custom:
  buckets:
    ASSETS_BUCKET_NAME: ${self:service}-${self:provider.stage}
    STATIC_BUCKET_NAME: ${self:service}-static
  apigwBinary:
    types:
      - '*/*'
  serverless-offline:
    noPrependStageInUrl: true
    httpPort: 4400
  customDomain:
    domainName: ${env:DOMAIN}
    basePath: ''
    stage: ${self:provider.stage}
    createRoute53Record: true
  s3Sync:
    - bucketName: ${self:custom.buckets.STATIC_BUCKET_NAME}
      localDir: src/static
      acl: public-read
  nuxt:
    version: v${file(./package.json):version}
    bucketName: ${self:custom.buckets.ASSETS_BUCKET_NAME}
    # cdnPath:
    # assetsPath:
    # assetsCacheMaxAge:

resources:
  Resources:
    AssetsBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.nuxt.bucketName}
        CorsConfiguration:
          CorsRules:
            - AllowedMethods:
              - GET
              - HEAD
              AllowedOrigins:
              - https://${env:DOMAIN}
    StaticBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.buckets.STATIC_BUCKET_NAME}
        CorsConfiguration:
          CorsRules:
            - AllowedMethods:
              - GET
              - HEAD
              AllowedOrigins:
              - https://${env:DOMAIN}

functions: ...
```

Everything is being uploaded correctly, but the rendered site is looking the assets in `/__nuxt/...`, 🤔 😩 

Any help is appreciate it!! thanks again
